### PR TITLE
Whitelist API Additions

### PR DESCRIPTION
**Pull request by samoehlert**
In order to get the API endpoint for the whitelist working, we had to add a url and a class for it. Feel free to change anything if there's a better way to do it.

### CODE REVIEW

**Comment by JustinAzoff** [comment]
Hi!  So this is weird.. view.py already has a `WhitelistViewSet` defined and urls.py has

    router.register(r'whitelist', views.WhitelistViewSet)

I could use some tests for it.. and the functions in bhr-client for it, but it should have already been functional.

I just started up the bhr instance I have at home and /bhr/api listed whitelist and I was able to click that and then use the built in form to create a whitelist entry.

This also works:

```
http --form --auth  admin:admin POST http://bhr.home/bhr/api/whitelist/ why='internal' cidr=10.0.0.0/8
HTTP/1.1 201 Created
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Type: application/json
Date: Thu, 15 Jun 2017 01:15:50 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "added": "2017-06-15 01:15:50.048176+00:00", 
    "cidr": "10.0.0.0/8", 
    "who": "admin", 
    "why": "internal"
}

```

I think the main thing I see missing is that the serializer isn't including the id and or url to the entry, so there's no easy way to delete/update one of the entries with the api.

**Comment by samoehlert** [comment]
Interesting. I somehow missed those, but when I remove what I've added, nothing happens. Nothing gets added to the whitelist using the command

```
curl -X POST -H "Authorization: Token $TOKEN" --data-urlencode why="test" --data-urlencode cidr=1.2.3.4/32 https://bhr-endpoint.example.com/bhr/api/whitelist
```

I think my original work may have come about due to red herring though. I was seeing some 500 errors when trying things before. Those don't seem to happen now, just not getting added (this test was done with just your code present, no patch from us). So I think my patch is probably pointless after all, but something is still not right. I can't add things via API using a fully up to date pull of your code.

**Comment by JustinAzoff** [comment]
ah!  Try adding a trailing slash to the URL you are using.

**Comment by samoehlert** [comment]
Sigh. That did it. Sorry for the noise.

**Comment by JustinAzoff** [comment]
No problem :-)  There is still a bit of work to do with the whitelist api anyway :-)

**Pull request closed without merging**
